In [118]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler,normalize



In [154]:
def process_data(file, lags):
    """Process data
    Reshape and split train\test data.
    # Arguments
        train: String, name of .csv train file.
        test: String, name of .csv test file.
        lags: integer, time lag.
    # Returns
        X_train: ndarray.
        y_train: ndarray.
        X_test: ndarray.
        y_test: ndarray.
        scaler: StandardScaler.
    """
    
#     read csv file
    df = pd.read_csv("/Users/ditlswin/Documents/rkaul/traffic_flow_predi/TrafficFlowPrediction-master/data/{}".format(file), encoding='utf-8',header=None).fillna(0)

#   read all the vehicle/15min in one array   
    flow = np.array(df.iloc[:,3:])
    flow = flow.ravel()

    
#     normalize all the values  
    scaler = MinMaxScaler(feature_range=(0, 1)).fit(flow.reshape(-1, 1))
    normalized_flow = scaler.transform(flow.reshape(-1, 1)).reshape(1, -1)[0]
    

#     splitting the file into train and test dataset
    split = int(normalized_flow.shape[0] * 0.8)
    
    flow1 = normalized_flow[:split]
    flow2 = normalized_flow[split:]
    
    
    train, test = [], []
    for i in range(lags, len(flow1)):
        train.append(flow1[i - lags: i + 1])
    for i in range(lags, len(flow2)):
        test.append(flow2[i - lags: i + 1])

    train = np.array(train)
    print(train)
    test = np.array(test)
    np.random.shuffle(train)

    X_train = train[:, :-1]
    print(X_train.shape)
    y_train = train[:, -1]
    print(y_train.shape)
    X_test = test[:, :-1]
    y_test = test[:, -1]

    return X_train, y_train, X_test, y_test, scaler

In [155]:
X_train, y_train, X_test, y_test, scaler = process_data("970_1_data.csv", 12)

[[0.19111111 0.18444444 0.11555556 ... 0.03555556 0.05333333 0.05555556]
 [0.18444444 0.11555556 0.12888889 ... 0.05333333 0.05555556 0.05555556]
 [0.11555556 0.12888889 0.13111111 ... 0.05555556 0.05555556 0.03333333]
 ...
 [0.64888889 0.74444444 0.72222222 ... 0.78888889 0.73555556 0.66444444]
 [0.74444444 0.72222222 0.76444444 ... 0.73555556 0.66444444 0.60666667]
 [0.72222222 0.76444444 0.83333333 ... 0.66444444 0.60666667 0.53333333]]
(2368, 12)
(2368,)


[[0.02346145 0.02049874 0.02049874 ... 0.01145047 0.00872798 0.0101693 ]
 [0.00056051 0.00064059 0.00048044 ... 0.00112103 0.00248227 0.00248227]
 [0.0012011  0.00072066 0.00072066 ... 0.00072066 0.00032029 0.00088081]
 ...
 [0.00216198 0.00216198 0.00128117 ... 0.00064059 0.00040037 0.00024022]
 [0.0012011  0.00112103 0.00040037 ... 0.00080073 0.0020819  0.00200183]
 [0.00136124 0.0012011  0.00088081 ... 0.00072066 0.0012011  0.00128117]] [0.01040952 0.00504461 0.00136124 ... 0.00056051 0.00352322 0.00144132]
